openapi: 3.0.0
info:
  title: "User Profile API"
  description: "API for managing Users"
  version: "1.0.0"

servers:
  - url: "/api"

components:
  schemas:
    User:
      type: "object"
      required:
        - first_name
        - last_name
        - email
        - role_id
        - location_id
      properties:
        first_name:
          type: "string"
        last_name:
          type: "string"
        email:
          type: "string"
        phone_number:
          type: "string"
        role_id:
          type: "integer"
        location_id:
          type: "integer"
        about_me:
          type: "string"
        height:
          type: "number"
        weight:
          type: "number"
        birthday:
          type: "string"
          format: "date"
        password:
          type: "string"
    

    Role:
      type: "object"
      required:
        - role_name
      properties:
        role_id:
          type: "integer"
          readOnly: true
        role_name:
          type: "string"

  parameters:
    user_id:
      name: "user_id"
      description: "ID of the user"
      in: path
      required: True
      schema:
        type: "integer"

paths:
  /users:
    get:
      operationId: "users.read_all"
      tags:
        - "Users"
      summary: "Read the list of users"
      responses:
        "200":
          description: "Successfully fetched users"
    
    post:
      operationId: "users.create"
      tags:
        - Users
      summary: "Create a new user"
      requestBody:
        description: "User to create"
        required: True
        content:
          application/json:
            schema:
              x-body-name: "user_data"
              $ref: "#/components/schemas/User"
      responses:
        "201":
          description: "Successfully created user"
          
  /users/{user_id}:
    get:
      operationId: "users.read_one"
      tags:
        - Users
      summary: "Read one user by ID"
      parameters:
        - $ref: "#/components/parameters/user_id"
      responses:
        "200":
          description: "Successfully read user"
        "404":
          description: "User not found"
    
    put:
      tags:
        - Users
      operationId: "users.update"
      summary: "Update a user"
      parameters:
        - $ref: "#/components/parameters/user_id"
      requestBody:
        content:
          application/json:
            schema:
              x-body-name: "user_data"
              $ref: "#/components/schemas/User"
      responses:
        "200":
          description: "Successfully updated user"

    delete:
      tags:
        - Users
      operationId: "users.delete"
      summary: "Delete a user"
      parameters:
        - $ref: "#/components/parameters/user_id"
      responses:
        "204":
          description: "Successfully deleted user"
  



  /roles:
    get:
      operationId: "roles.read_all"
      tags:
        - "Roles"
      summary: "Read the list of all roles"
      responses:
        "200":
          description: "Successfully fetched roles"
          content:
            application/json:
              schema:
                type: "array"
                items:
                  $ref: "#/components/schemas/Role"
    post:
      operationId: "roles.create"
      tags:
        - "Roles"
      summary: "Create a new role"
      requestBody:
        description: "Role to create"
        required: true
        content:
          application/json:
            schema:
              x-body-name: "role_data"
              $ref: "#/components/schemas/Role"
      responses:
        "201":
          description: "Successfully created role"
        "406":
          description: "Role already exists"

  /roles/{role_id}:
    get:
      operationId: "roles.read_one"
      tags:
        - "Roles"
      summary: "Read one role"
      parameters:
        - name: "role_id"
          in: path
          required: true
          schema:
            type: "integer"
      responses:
        "200":
          description: "Successfully read role"
        "404":
          description: "Role not found"
    
    put:
      operationId: "roles.update"
      tags:
        - "Roles"
      summary: "Update a role"
      parameters:
        - name: "role_id"
          in: path
          required: true
          schema:
            type: "integer"
      requestBody:
        content:
          application/json:
            schema:
              x-body-name: "role_data"
              $ref: "#/components/schemas/Role"
      responses:
        "200":
          description: "Successfully updated role"
        "404":
          description: "Role not found"

    delete:
      operationId: "roles.delete"
      tags:
        - "Roles"
      summary: "Delete a role"
      parameters:
        - name: "role_id"
          in: path
          required: true
          schema:
            type: "integer"
      responses:
        "204":
          description: "Successfully deleted role"
        "404":
          description: "Role not found"